### ISSUE TITLE
Creating rate limiting rules impeded by shield duplicate rule names

### ISSUE THREAD

**Issue by theaupoulat** [teamplanes/graphql-rate-limit#159]
* **I'm submitting a ...**
[x] question about how to use this project

* **Summary**

`js

// in schema
const GraphQLRateLimit = createRateLimitRule({
	identifyContext: (ctx) => ctx.ip,

	store: new RedisStore(redis),
});

const rateLimitedQueriesAndMutations = getRateLimits({
	long: 1,
	normal: 3,
	fast: 5,
	rateLimitRuleInstance: GraphQLRateLimit,
});

// function 

export const getRateLimits = ({
	long,
	normal,
	fast,
	window,
	rateLimitRuleInstance,
}: {
	long: number,
	normal: number,
	fast: number,
	window: string,
	rateLimitRuleInstance: any,
}) => {
	return {
		Query: {
			user: rateLimitRuleInstance({ window, max: fast }),
		 	retrieveUser: rateLimitRuleInstance({ window, max: fast }),
                       [rest of queries ...]
                }
      }
}
`

When executed, I get this error: 

`uncaughtException: There seem to be multiple definitions of these rules: 0.174264369447499`

Should I create an instance the rate limit rule for each queries ?

Stacktrace : 

`
 error: uncaughtException: There seem to be multiple definitions of these rules: 0.174264369447499
I20200723-19:15:07.919(2)? Error: There seem to be multiple definitions of these rules: 0.174264369447499
I20200723-19:15:07.919(2)?     at shield (/Users/theaupoulat/Documents/pytheas/pca-onboarding/node_modules/graphql-shield/dist/shield.js:46:15)
I20200723-19:15:07.919(2)?     at module (imports/api/schema.js:63:21)
I20200723-19:15:07.919(2)?     at fileEvaluate (packages/modules-runtime.js:336:7)
I20200723-19:15:07.919(2)?     at Module.require (packages/modules-runtime.js:238:14)
I20200723-19:15:07.919(2)?     at Module.moduleLink [as link] (/Users/theaupoulat/.meteor/packages/modules/.0.15.0.1ipozqj.rpnt++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
I20200723-19:15:07.920(2)?     at module (/private/var/folders/d4/l3z1_xmx3tqb07fq354m7njr0000gn/T/meteor-test-run18uruvh.xvzw/.meteor/local/build/programs/server/app/app.js:15246:8)
I20200723-19:15:07.920(2)?     at fileEvaluate (packages/modules-runtime.js:336:7)
I20200723-19:15:07.920(2)?     at Module.require (packages/modules-runtime.js:238:14)
I20200723-19:15:07.920(2)?     at Module.moduleLink [as link] (/Users/theaupoulat/.meteor/packages/modules/.0.15.0.1ipozqj.rpnt++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
I20200723-19:15:07.920(2)?     at module (imports/startup/server/index.js:1:1)
I20200723-19:15:07.920(2)?     at fileEvaluate (packages/modules-runtime.js:336:7)
I20200723-19:15:07.920(2)?     at Module.require (packages/modules-runtime.js:238:14)
I20200723-19:15:07.920(2)?     at Module.moduleLink [as link] (/Users/theaupoulat/.meteor/packages/modules/.0.15.0.1ipozqj.rpnt++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
I20200723-19:15:07.920(2)?     at module (server/main.js:1:8)
I20200723-19:15:07.920(2)?     at fileEvaluate (packages/modules-runtime.js:336:7)
I20200723-19:15:07.920(2)?     at Module.require (packages/modules-runtime.js:238:14)
I20200723-19:15:07.920(2)?     at require (packages/modules-runtime.js:258:21)
I20200723-19:15:07.921(2)?     at apollo.config.js:1:1
I20200723-19:15:07.921(2)?     at /private/var/folders/d4/l3z1_xmx3tqb07fq354m7njr0000gn/T/meteor-test-run18uruvh.xvzw/.meteor/local/build/programs/server/boot.js:401:38
I20200723-19:15:07.921(2)?     at Array.forEach (<anonymous>)
I20200723-19:15:07.921(2)?     at /private/var/folders/d4/l3z1_xmx3tqb07fq354m7njr0000gn/T/meteor-test-run18uruvh.xvzw/.meteor/local/build/programs/server/boot.js:226:21
I20200723-19:15:07.921(2)?     at /private/var/folders/d4/l3z1_xmx3tqb07fq354m7njr0000gn/T/meteor-test-run18uruvh.xvzw/.meteor/local/build/programs/server/boot.js:464:7
I20200723-19:15:07.921(2)?     at Function.run (/private/var/folders/d4/l3z1_xmx3tqb07fq354m7njr0000gn/T/meteor-test-run18uruvh.xvzw/.meteor/local/build/programs/server/profile.js:280:14)
I20200723-19:15:07.921(2)?     at /private/var/folders/d4/l3z1_xmx3tqb07fq354m7njr0000gn/T/meteor-test-run18uruvh.xvzw/.meteor/local/build/programs/server/boot.js:463:13
`

**Comment by Bram-Zijp** [comment]
My use cases look very different. Could you make an reproduction one can play around with?

**Comment by schester44** [comment]
I'm running into this same error... "There seem to be multiple definitions of these rules: 0.419744850926866"

```js
const rateLimitRule = createRateLimitRule({
  identifyContext: (ctx: Context) => {
    return ctx.currentUser.id
  },
});
```

```
   Mutation: {
      createPaymentMethod: and(
        isClientMember,
        rateLimitRule({ window: "1s", max: 10 })
      ),
      createQuoteRequest: and(allow, rateLimitRule({ window: "1s", max: 10 })),
}
```

**Comment by schester44** [comment]
Unrelated to this issue, but i'm also seeing these errors in our CI env. Possible dependency version mismatch?

```
../node_modules/graphql-rate-limit/node_modules/graphql-shield/dist/constructors.d.ts:39:122 - error TS2694: Namespace '"/home/semaphore/project/node_modules/yup/lib/index"' has no exported member 'Schema'.00:17
39 export declare const inputRule: <T>(name?: string | undefined) => (schema: (yup: typeof Yup, ctx: IShieldContext) => Yup.Schema<T, object>, options?: Yup.ValidateOptions<object> | undefined) => InputRule<T>;
```

**Comment by rezaSh1001** [comment]
I also get this error when using `rateLimitRule` multiple times

```javascript
const rateLimitRule = createRateLimitRule({
    identifyContext: (ctx) => ctx.ip,
})

const isAuthenticated = rule()((parent, args, { user }, info) => user !== null)

const tenTimesPerHourRule = rateLimitRule({ window: '1h', max: 10 })
const twoTimesPerHourRule = rateLimitRule({ window: '1h', max: 2 })

return shield(
    {
        Query: {
            login: tenTimesPerHourRule,
            info: and(isAuthenticated, twoTimesPerHourRule),
        },
    },
    {
        allowExternalErrors: true,
    }
)
```

after i look to source code i find out `createRateLimitRule` create one instance of Shield Rule and use that on every call of returned function and this cause the issue

```javascript
const createRateLimitRule = (
  config: GraphQLRateLimitConfig
): ((fieldConfig: GraphQLRateLimitDirectiveArgs) => IRule) => {
  const noCacheRule = rule({ cache: 'no_cache' }); // THIS LINE COUSE THE ISSUE
  const rateLimiter = getGraphQLRateLimiter(config);

  return (fieldConfig: GraphQLRateLimitDirectiveArgs) =>
//IT MUST BE HERE OR SOMETHING LIKE THIS WILL FIX THE ISSUE rule({ cache: 'no_cache' })(async (parent, args, context, info)
    noCacheRule(async (parent, args, context, info) => { 
      const errorMessage = await rateLimiter(
        {
          parent,
          args,
          context,
          info: info as GraphQLResolveInfo, // I hope this is so.
        },
        fieldConfig
      );

      if (errorMessage) {
        return config.createError
          ? config.createError(errorMessage)
          : new RateLimitError(errorMessage);
      }

      return true;
    });
};
```

**Comment by simplecommerce** [comment]
I have the same issue mentioned here when trying to use it with graphql-shield.

**Comment by theaupoulat** [comment]
> My use cases look very different. Could you make an reproduction one can play around with?

Hey sorry, I don't work in the same company so I don't have access to that code anymore. Sorry and good luck.

**Comment by YuriFontella** [comment]
+1

is there already a solution for this?

**Comment by kirkness** [comment]
#185 is published in `3.2.0`
