### ISSUE TITLE
Error on import - TypeError: utilities_1.getIntrospectionQuery is not a function

### ISSUE THREAD

**Issue by neubee** [teamplanes/graphql-rate-limit#64]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ X ] question about how to use this project

* **Summary**
Not sure if this is a bug report, or if I'm just using the package incorrectly.
I've added the package to my project and now when I try to use one of the import statements my app crashed and throws this error `TypeError: utilities_1.getIntrospectionQuery is not a function`.
This happens with any of the import options listed in the documentation, but I am specifically trying to use `import { getGraphQLRateLimiter } from 'graphql-rate-limit';`.
Any insight or help you can give on what is happening here would be appreciated.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Full error
```
TypeError: utilities_1.getIntrospectionQuery is not a function
    at Object.<anonymous> (D:\IAmEric_2\Documents\work\bitsy-boxes\development\LittleBackend\node_modules\graphql-rate-limit\node_modules\graphql-tools\src\stitching\introspectSchema.ts:8:54)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .js] (D:\IAmEric_2\Documents\work\bitsy-boxes\development\LittleBackend\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (D:\IAmEric_2\Documents\work\bitsy-boxes\development\LittleBackend\node_modules\graphql-rate-limit\node_modules\graphql-tools\src\stitching\index.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .js] (D:\IAmEric_2\Documents\work\bitsy-boxes\development\LittleBackend\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (D:\IAmEric_2\Documents\work\bitsy-boxes\development\LittleBackend\node_modules\graphql-rate-limit\node_modules\graphql-tools\src\index.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .js] (D:\IAmEric_2\Documents\work\bitsy-boxes\development\LittleBackend\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (D:\IAmEric_2\Documents\work\bitsy-boxes\development\LittleBackend\node_modules\graphql-rate-limit\src\lib\field-directive.ts:10:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .js] (D:\IAmEric_2\Documents\work\bitsy-boxes\development\LittleBackend\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (D:\IAmEric_2\Documents\work\bitsy-boxes\development\LittleBackend\node_modules\graphql-rate-limit\src\index.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .js] (D:\IAmEric_2\Documents\work\bitsy-boxes\development\LittleBackend\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (D:/IAmEric_2/Documents/work/bitsy-boxes/development/LittleBackend/graphql/defs/user/user.directives.js:30:31)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at loader (D:\IAmEric_2\Documents\work\bitsy-boxes\development\LittleBackend\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (D:\IAmEric_2\Documents\work\bitsy-boxes\development\LittleBackend\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (D:/IAmEric_2/Documents/work/bitsy-boxes/development/LittleBackend/graphql/schema/resolvers.js:15:23)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at loader (D:\IAmEric_2\Documents\work\bitsy-boxes\development\LittleBackend\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (D:\IAmEric_2\Documents\work\bitsy-boxes\development\LittleBackend\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (D:/IAmEric_2/Documents/work/bitsy-boxes/development/LittleBackend/graphql/schema/index.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at loader (D:\IAmEric_2\Documents\work\bitsy-boxes\development\LittleBackend\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (D:\IAmEric_2\Documents\work\bitsy-boxes\development\LittleBackend\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (D:/IAmEric_2/Documents/work/bitsy-boxes/development/LittleBackend/server.js:90:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at loader (D:\IAmEric_2\Documents\work\bitsy-boxes\development\LittleBackend\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (D:\IAmEric_2\Documents\work\bitsy-boxes\development\LittleBackend\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (D:\IAmEric_2\Documents\work\bitsy-boxes\development\LittleBackend\index.js:25:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

Other dependencies used in the project
```
"dependencies": {
    "@sendgrid/mail": "^6.2.1",
    "apollo-server-express": "^1.1.2",
    "aws-sdk": "^2.203.0",
    "aws-xray-sdk": "^2.2.0",
    "axios": "^0.17.1",
    "babel-polyfill": "^6.9.1",
    "body-parser": "^1.17.2",
    "compression": "^1.6.2",
    "cors": "^2.8.4",
    "cross-env": "^1.0.8",
    "express": "^4.15.4",
    "express-graphql": "^0.6.7",
    "express-winston": "^3.2.1",
    "fast-xml-parser": "^3.12.16",
    "graphql": "^0.11.2",
    "graphql-date": "^1.0.3",
    "graphql-rate-limit": "^2.0.1",
    "graphql-tools": "^1.2.2",
    "hashids": "^1.1.4",
    "jsonwebtoken": "^8.0.0",
    "lodash": "^4.17.4",
    "moment": "^2.18.1",
    "mongoose": "^4.4.20",
    "qs": "^6.5.2",
    "raven": "^2.4.1",
    "shortid": "^2.2.8",
    "stripe": "^5.4.0",
    "webpack": "2.1.0-beta.8",
    "webpack-dev-middleware": "^1.6.1",
    "webpack-dev-server": "^2.1.0-beta.0",
    "webpack-externals-plugin": "^1.0.0",
    "webpack-hot-middleware": "^2.10.0",
    "winston": "^3.2.1"
  },
  "devDependencies": {
    "ava": "^0.25.0",
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-eslint": "^6.0.4",
    "babel-loader": "^6.2.4",
    "babel-plugin-webpack-loaders": "^0.7.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-es2015-native-modules": "^6.6.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-react-optimize": "^1.0.1",
    "babel-preset-stage-0": "^6.5.0",
    "babel-register": "^6.9.0",
    "chunk-manifest-webpack-plugin": "^1.1.2",
    "eslint": "^2.11.1",
    "eslint-config-airbnb": "^9.0.1",
    "eslint-plugin-ava": "^2.4.0",
    "eslint-plugin-import": "^1.8.1",
    "eslint-plugin-jsx-a11y": "^1.3.0",
    "eslint-plugin-react": "^5.1.1",
    "eventsource-polyfill": "^0.9.6",
    "extract-text-webpack-plugin": "^2.1.2",
    "html-webpack-plugin": "^2.30.1",
    "json-loader": "^0.5.4",
    "nodemon": "^1.9.2",
    "pre-commit": "^1.2.2",
    "proxyquire": "^2.1.0",
    "sinon": "^7.2.2",
    "webpack-node-externals": "^1.6.0"
  },
```

**Comment by neubee** [comment]
Found out that my old version of the graphql package was causing this error. After upgrading to a newer version (specifically 14.1.1), the import worked just fine.
